module.exports = [
	"The Pepper",
	"Cranberry sauce",
	"Krisp Cricket Crunch",
	"Catch Phrase",
	"Swamp Walk",
	"Thanksgiving Chistmas Carols",
	"\"There's a right way and a wrong way\"",
	"Skinny-dipping",
	"\"Is that Mr. Jackass?\"",
	"\"Donde estan my choos?\"",
	"The \"little kid's\" table",
	"Plays by the cousins",
	"Christmas Eve present",
	"Hack and schpit",
	"\"Go tell eet on zee mountain\"",
	"Getting to know you",
	"\"What\'n more?\"",
	"\"Car!\"",
	"625 Dauphine St.",
	"Cocoa",
	"Fiddledeedee",
	"The Old Farmhouse",
	"Pfaffnwer",
	"Wine",
	"Tannin",
	"Roast beast",
	"Count mushrooms",
	"Horti culture",
	"Punny",
	"Clever",
	"Creative",
	"The Keg",
	"Tivoli",
	"Twins",
	"Brocolli Casserole",
	"Oyster Jacuzzi",
	"Picayune",
	"Brünhilde",
	"\"Breath of Fresh Air\"",
	"Sailboat",
	"Shoes on a Kite",
	"Turkey stuffing",
	"Sanibel Island",
	"Petri Dish",
	"Cajon cruise",
	"Frozen pipes",
	"\"I love y'all\"",
	"\"Bwah ha ha\"",
	"\"Oh fiddle dee dee\"",
	"Schlock",
	"Touch titty",
	"I can't beleive I ate...",
	"Spaceteam",
	"Wine",
	"Puns",
	"Cutinary",
	"Shooose",
	"Catch phrase",
	"Scrabble",
	"Laughter",
	"Long break scats",
	"\"I'm DESPERATE for...\"",
	"\"I DESPRATELY need...\"",
	"\"Ex-CUSE me...\"",
	"\"Let me count the ribbons...\"",
	"Hilarious",
	"\"Let me check my diary\"",
	"KickAssteroids",
	"StackIt",
	"LaughItUp",
	"\"Where is the Prozae?\"",
	"Fum",
	"Loving",
	"\"You said WHAT?\"",
	"Fabulous fun loving family",
	"Fun",
	"Loving",
	"Voluable",
	"\"So there was a snail...\"",
	"\"Look at that ES-CAR-GO(t)!\"",
	"Coldwater",
	"Creative",
	"Individual",
	"Funny",
	"Loving",
	"Accepting",
	"Chocolate",
	"Caring",
	"Kind",
	"Foodies",
	//"\"If you want it done differently, do it yourself.\"",
	"Far-legged family",
	"Snow",
	"242-5940",
	"\"DAMMIT DAMMIT DAMMIT!\"",
	"Bredericksburg",
	"The Lone Star State",
	"Mardi Gras",
	"Blah",
	"A.R.F.",
	"\"You idiots, we have THREE MINUTES!\"",
	"\"Let's use a *REAL* camera!\"",
	"\"He just wants to put the roach up...\""
]